### ISSUE TITLE
all stream

### ISSUE THREAD

**Issue by BlackGlassSkin** [srg70/pvr.puzzle.tv#1]
Does it work on user lists?
I was looking for an option but not reading my lists
I also tried with the server from xbmc.ru

I have several lists from the archive of 3, 5 and 7 days but none work

**Comment by srg70** [comment]
Yes, it works with customer's playlist. You may put your list in either Edem or Shara slot. Please note, not all tags are supported by add-on. Same for archive support. It works but or certain formats.

**Comment by BlackGlassSkin** [comment]
very nice addon !!!
Thanks, I found on the forum that it works with edem, I haven't tested shar tv yet, the recording works ok,

channel index offset = epg timeshift?  1 , 0 , -1 something like this?

and the last question, a lot of skins have been applied

**PVR-HasArchive.png** or **archive.png**
+ patch added to variables.xml, 

do you have the option of adding something like that

I know that pvrarchive in coreelec could be an excellent example

and what must be the m3u mark for the archive
timeshift="3"
catchup-source"3"
?utc={utc}&lutc={lutc}

================================

does not work on libreelec Generic 9.2.0

I tried to compile a version for this system

-- Configuring incomplete, errors occurred!
See also "/root/Desktop/pvr.iptvsimple/build/build/curl/src/curl-build/CMakeFiles/CMakeOutput.log".
CMakeFiles/curl.dir/build.make:108: recipe for target 'build/curl/src/curl-stamp/curl-configure' failed
make[2]: *** [build/curl/src/curl-stamp/curl-configure] Error 1
CMakeFiles/Makefile2:240: recipe for target 'CMakeFiles/curl.dir/all' failed
make[1]: *** [CMakeFiles/curl.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
root@my:~/Desktop/pvr.iptvsimple/build#

full:
https://privatebin.net/?947f1947dd542770#9eRbaaPRxQqGPmAfro9pBfEbGHcJjp7Z9z7GVdiTVZCx

**Comment by srg70** [comment]
Thanks for good words, but the addon is in development state, so not all feature are working the best way. 
1. Regarding link format for archive... For historical reasons Edem implements a special case. This slot just adds  ?utc={utc}&lutc={lutc} for every channel in list, for 3 days. Shara TV slot is more advanced. It supports tvg-id, catchup, catchup-days, catchup-source, etc tags. Somewhen I'll concatinate them into one slot for playlist.
2. As far as I know, PVR has no access for properties of skin objects. Additionaly, CoreElec applied modification on Kodi's source code to success with archive support. This project supports only generic Kodi interface.
3. Your build is failed because I run it with Docker, and some scripts assume that enviroument, unfortunately. I have no option to check your setup, but you can try to declare enviroument variable  DEFAULT_DOCKCROSS_IMAGE with value dockcross/linux-x64 (if your platfom is 64-bit PC)

**Comment by BlackGlassSkin** [comment]
I can't handle this compilation

can you improve the libreelec version yourself

this version works fine on libre if it helps

https://github.com/kodi-pvr/pvr.iptvsimple/releases/tag/3.8.8-Leia

kodi
https://github.com/xbmc/xbmc/tree/Leia

work great for latest libreelec 9.2.0 generic

===================================
I am looking forward to further development
this is very much needed for all platforms
I have no idea why Kodi can't do this

**Comment by srg70** [comment]
I have no compilation issue, so I can't fix it. You may want to compile with Docker as well.
Also It is not clear why do you need to compile from source, when you can install it from the repo. 

The latest suggesrtion is not clear for me, sorry.

**Comment by BlackGlassSkin** [comment]
**libreelec 9.2.0 , kodi 18.5 not work** 

windows x64 kodi 18.6 work
Android - dont  know
Linux - dont know / i use linux only on vps

I will try to delete these 2 lines
pvr doesn't need them 

import addon="kodi.binary.global.gui" version="5.12.0"
import addon="kodi.binary.global.filesystem" version="1.0.2"


and kodi.binary.global.gui is 5.14.0 I think the problem is here

**thanks for the answers and hints**

**regards!**

**Comment by srg70** [comment]
To understand better the reason of failure please provide Kodi.log file in debug mode.

**Comment by BlackGlassSkin** [comment]
https://hastebin.com/jayufafoja.sql

**Comment by srg70** [comment]
_reason: /storage/.kodi/addons/pvr.puzzle.tv/pvr.puzzle.tv.so.0.9.60: cannot open shared object file: No such file or directory_
No issue with dependencies. This problem been discussed on forum few times. For unknown reason somewhen the add-on's archive becomes corrupted after downloading. Please check the archive size.

**Comment by BlackGlassSkin** [comment]
the problem is I haven't added anything yet
addon is not configured yet, only clean installation

I was also looking in the forum but I have to translate everything in Google translator and it will take some time before I go over 150 pages

**Comment by srg70** [comment]
It failed on installation phase. You can't configure anything because installation fails. 
Again, check the archive for errors, or even install manually from zip.

**Comment by BlackGlassSkin** [comment]
I see that you did update, now everything has been installed correctly on libreelec but cannot run any program

the same list and settings I have on windows 10 x64 everything works

on LibreELEC, unfortunately, does not work  [some of the logos below]


https://hastebin.com/ijudomebeq.sql

**Comment by srg70** [comment]
The issue is not with the list or settings, but with OpenSSL system library. I have no experience in this area, unfortunately. Hopefully somewhen in the future I'll find solution, but now I have no idea how to fix it, sorry. 

PS: you may try to look into debug log with CURL component turned ON. It should contain more details regarding connection handshake.

**Comment by BlackGlassSkin** [comment]
Thx
I hope you will develop this addon to perfection

Regards

**Comment by srg70** [comment]
FYI: OpenSSL issue has been fixed with latest versions.
